updates

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -3,35 +3,86 @@
 # Nginx where it should be listening on port 80
 # Serve a page that would return a Hello World string
 
-# Updating and installing nginx
-sudo apt update
-sudo apt install -y nginx
+# colors
+blue='\e[1;34m'
+yellow='\e[0;33m'
+green='\e[1;32m'
+reset='\033[0m'
 
-# starting nginx service
-sudo service nginx start
+echo -e "${blue}Updating and doing some minor checks...${reset}\n"
+
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: ${yellow}$1${reset}\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${green}${1} is already installed.${reset}\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\n${blue}Setting up some minor stuff.${reset}\n"
 
 # allowing nginx on firewall
 sudo ufw allow 'Nginx HTTP'
 
 # Give the user ownership to website files for easy editing
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
 
-# Creating new index
-echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
 
-# Setting up /redirect_me to my github profile
-sudo sed -i '24i\       rewrite ^/redirect_me https://github.com/jesse-jagger permanent;' /etc/nginx/sites-available/default
+# creating new index
+echo "Hello World!" > /var/www/html/index.html
 
-# Set up a 404 page
-echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
-sudo sed -i '25i\       error_page 404 /error_404.html;' /etc/nginx/sites-available/default
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-# http header respons
-sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-# Test syntax error
-sudo nginx -t
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
 
-# restart server
-sudo service nginx restart
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
